### ISSUE TITLE
Link on old googlecode site is wrong

### ISSUE THREAD

**Issue by chelmuth** [SuperTux/SuperTux.github.io-archived#5]
I do not know if this is the right place, but maybe the devs also listen here. The link on http://supertux.googlecode.com points to https://github.com/SuperTuxTeam/ but should be https://github.com/SuperTux or even better http://supertux.github.io/.

**Comment by maxteufel** [comment]
According to @tobbi, someone with admin access to the Google Code project needs to change this (if it's possible).

**Comment by tobbi** [comment]
I have sent an e-mail to Google Code admins and requested to change the redirection link

**Comment by tobbi** [comment]
Google admins have gotten back to me. link was changed.
